version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table containing AirBnB listings.
    columns: 
      - name: listing_id
        description: Primary key for listings table
        tests:
          - unique
          - not_null
      - name: host_id
        description: Foreign key to the hosts table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Room/apartment type
        tests:
          - accepted_values:
              values: [
                'Entire home/apt',
                'Private room',
                'Shared room',
                'Hotel room'
              ]
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
        - positive_values